### ISSUE TITLE
x-ui功能集成

### ISSUE THREAD

**Issue by ttlttc** [csznet/goForward#1]
尝试了一下,轻量化很好用,不过直接暴露在公网上还是不太安全,建议先借鉴xui的相关实现

1.自定义路径伪装   ip:port/a1b2c3d4
2.面板访问密码

然后现在用ip:8080/8889都可以访问,第一条规则的存在意义不大,最好有个设置能修改默认端口.然后这个规则目前删除了进程就崩溃,下次开启又会自动创建,可以优化一下

**Comment by csznet** [comment]
面板访问密码已经增加，感谢支持
