### ISSUE TITLE
可以自己指定db文件存放位置吗

### ISSUE THREAD

**Issue by Waitung** [csznet/goForward#12]
没找到这个的设置，默认同一个目录放在在 bin 里有点乱

**Comment by csznet** [comment]
已在新版本中添加

**Comment by Waitung** [comment]
测试好像不生效
![Clip_20240418_222252](https://github.com/csznet/goForward/assets/37104069/6741e04b-c681-4d77-99c1-b17fb95c2cc2)

**Comment by csznet** [comment]
见新版本，已经完善。

**Comment by Waitung** [comment]
1.2.1版本测试已经可以了，感谢。
